import { zodResolver } from '@hookform/resolvers/zod'
import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { FiSave } from 'react-icons/fi'
import { Link } from 'react-router-dom'
import { z } from 'zod'

import DateInput from '../ui/DateInput.jsx'
import FormSelect from '../ui/FormSelect.jsx'
import { parseTags, PRACTICE_STATUSES, QUESTION_STATUSES, RESOURCE_STATUSES, RESOURCE_TYPES, todayValue } from './learning.constants.js'

const inputClass = 'mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-primary focus:ring-3 focus:ring-primary/10'
const ErrorText = ({ message }) => message ? <p className="mt-1.5 text-xs font-normal text-red-500">{message}</p> : null

function TopicSelect({ control, topics, error }) {
  return <label className="text-sm font-semibold text-[#555]">Learning Topic <span className="text-red-500">*</span><FormSelect name="topic" control={control} options={[{ value: '', label: 'Select a topic' }, ...topics.map((topic) => ({ value: topic._id, label: topic.title }))]} className="mt-1.5" /><ErrorText message={error} /></label>
}

function Actions({ cancelTo, submitting, label }) {
  return <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Link to={cancelTo} className="rounded-md bg-white px-5 py-2.5 text-center text-sm font-semibold text-[#555] hover:bg-[#f5f5f5]">Cancel</Link><button type="submit" disabled={submitting} className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-5 py-2.5 text-sm font-semibold text-white hover:bg-primary-dark disabled:opacity-60"><FiSave aria-hidden="true" /> {submitting ? 'Saving...' : label}</button></div>
}

const entrySchema = z.object({ topic: z.string().min(1, 'Learning Topic is required'), title: z.string().trim().min(1, 'Title is required').max(200), notes: z.string().max(15000), keyTakeaway: z.string().trim().min(1, 'Key takeaway is required').max(3000), entryDate: z.string().min(1, 'Date is required'), tags: z.string() })
export function EntryForm({ topics, tagSuggestions = [], initialValues = { topic: '', title: '', notes: '', keyTakeaway: '', entryDate: todayValue(), tags: '' }, onSubmit, submitting, serverError, cancelTo }) {
  const { register, control, handleSubmit, reset, watch, setValue, formState: { errors } } = useForm({ resolver: zodResolver(entrySchema), defaultValues: initialValues })
  useEffect(() => reset(initialValues), [initialValues, reset])
  const currentTags = watch('tags') || ''
  const addTag = (tag) => setValue('tags', [...new Set([...parseTags(currentTags), tag])].join(', '), { shouldDirty: true })
  return <form onSubmit={handleSubmit((values) => onSubmit({ ...values, tags: parseTags(values.tags) }))} noValidate className="space-y-3"><section className="rounded-lg bg-white p-4 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><TopicSelect control={control} topics={topics} error={errors.topic?.message} /><label className="text-sm font-semibold text-[#555]">Date <span className="text-red-500">*</span><DateInput {...register('entryDate')} className={inputClass} /><ErrorText message={errors.entryDate?.message} /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">Entry title <span className="text-red-500">*</span><input {...register('title')} className={inputClass} placeholder="Enter what you learned" /><ErrorText message={errors.title?.message} /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">Notes<textarea {...register('notes')} rows="7" className={`${inputClass} resize-y`} placeholder="Record useful details" /><ErrorText message={errors.notes?.message} /></label><label className="rounded-md bg-[#edf3f9] p-3 text-sm font-semibold text-[#315f91] sm:col-span-2">Key takeaway <span className="text-red-500">*</span><textarea {...register('keyTakeaway')} rows="4" className={`${inputClass} resize-y bg-white`} placeholder="Summarize what you actually understood" /><ErrorText message={errors.keyTakeaway?.message} /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">Tags<input {...register('tags')} className={inputClass} placeholder="Enter tags separated by commas" /></label>{tagSuggestions.length > 0 && <div className="sm:col-span-2"><p className="text-xs font-medium text-[#777]">Suggested tags</p><div className="mt-2 flex flex-wrap gap-2">{tagSuggestions.slice(0, 10).map((tag) => <button key={tag} type="button" onClick={() => addTag(tag)} className="rounded-full bg-[#f2f2f1] px-2.5 py-1 text-xs text-[#555] hover:bg-[#edf3f9] hover:text-[#315f91]">+ {tag}</button>)}</div></div>}</div></section>{serverError && <p className="rounded-md bg-red-50 px-4 py-3 text-sm text-red-600">{serverError}</p>}<Actions cancelTo={cancelTo} submitting={submitting} label="Save entry" /></form>
}

const resourceSchema = z.object({ topic: z.string().min(1, 'Learning Topic is required'), title: z.string().trim().min(1, 'Title is required').max(250), type: z.enum(RESOURCE_TYPES), url: z.string().trim().max(1000).refine((value) => !value || /^https?:\/\//i.test(value), 'URL must start with http:// or https://'), notes: z.string().max(5000), status: z.enum(RESOURCE_STATUSES) })
export function ResourceForm({ topics, initialValues = { topic: '', title: '', type: 'Article', url: '', notes: '', status: 'Saved' }, onSubmit, submitting, serverError, cancelTo }) {
  const { register, control, handleSubmit, reset, formState: { errors } } = useForm({ resolver: zodResolver(resourceSchema), defaultValues: initialValues })
  useEffect(() => reset(initialValues), [initialValues, reset])
  return <form onSubmit={handleSubmit(onSubmit)} noValidate className="space-y-3"><section className="rounded-lg bg-white p-4 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><TopicSelect control={control} topics={topics} error={errors.topic?.message} /><label className="text-sm font-semibold text-[#555]">Type<FormSelect name="type" control={control} options={RESOURCE_TYPES} className="mt-1.5" /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">Title <span className="text-red-500">*</span><input {...register('title')} className={inputClass} placeholder="Enter resource title" /><ErrorText message={errors.title?.message} /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">URL <span className="font-normal text-[#999]">(optional)</span><input type="url" {...register('url')} className={inputClass} placeholder="https://" /><ErrorText message={errors.url?.message} /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">Notes<textarea {...register('notes')} rows="5" className={`${inputClass} resize-y`} placeholder="Why is this resource useful?" /></label><label className="text-sm font-semibold text-[#555]">Status<FormSelect name="status" control={control} options={RESOURCE_STATUSES} className="mt-1.5" /></label></div></section>{serverError && <p className="rounded-md bg-red-50 px-4 py-3 text-sm text-red-600">{serverError}</p>}<Actions cancelTo={cancelTo} submitting={submitting} label="Save resource" /></form>
}

const practiceSchema = z.object({ topic: z.string().min(1, 'Learning Topic is required'), title: z.string().trim().min(1, 'Title is required').max(250), practiceGoal: z.string().trim().min(1, 'Practice goal is required').max(5000), practiceDate: z.string().min(1, 'Date is required'), whatHappened: z.string().max(5000), wentWell: z.string().max(5000), wentWrong: z.string().max(5000), improveNext: z.string().max(5000), status: z.enum(PRACTICE_STATUSES) })
export function PracticeForm({ topics, initialValues = { topic: '', title: '', practiceGoal: '', practiceDate: todayValue(), whatHappened: '', wentWell: '', wentWrong: '', improveNext: '', status: 'Planned' }, onSubmit, submitting, serverError, cancelTo }) {
  const { register, control, handleSubmit, reset, formState: { errors } } = useForm({ resolver: zodResolver(practiceSchema), defaultValues: initialValues })
  useEffect(() => reset(initialValues), [initialValues, reset])
  const area = (name, label, placeholder) => <label className="text-sm font-semibold text-[#555]">{label}<textarea {...register(name)} rows="4" className={`${inputClass} resize-y`} placeholder={placeholder} /><ErrorText message={errors[name]?.message} /></label>
  return <form onSubmit={handleSubmit(onSubmit)} noValidate className="space-y-3"><section className="rounded-lg bg-white p-4 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><TopicSelect control={control} topics={topics} error={errors.topic?.message} /><label className="text-sm font-semibold text-[#555]">Date <span className="text-red-500">*</span><DateInput {...register('practiceDate')} className={inputClass} /><ErrorText message={errors.practiceDate?.message} /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">Title <span className="text-red-500">*</span><input {...register('title')} className={inputClass} placeholder="Enter practice title" /><ErrorText message={errors.title?.message} /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">What do you want to practice? <span className="text-red-500">*</span><textarea {...register('practiceGoal')} rows="4" className={`${inputClass} resize-y`} placeholder="Describe the action you want to practice" /><ErrorText message={errors.practiceGoal?.message} /></label><label className="text-sm font-semibold text-[#555]">Status<FormSelect name="status" control={control} options={PRACTICE_STATUSES} className="mt-1.5" /></label></div></section><section className="rounded-lg bg-white p-4 sm:p-6"><h2 className="mb-4 text-lg font-semibold">Reflection</h2><div className="grid gap-4 sm:grid-cols-2">{area('whatHappened', 'What happened', 'Describe what happened')}{area('wentWell', 'What went well', 'Record what worked')}{area('wentWrong', 'What went wrong', 'Record what did not work')}{area('improveNext', 'What should improve next time', 'Write the next improvement')}</div></section>{serverError && <p className="rounded-md bg-red-50 px-4 py-3 text-sm text-red-600">{serverError}</p>}<Actions cancelTo={cancelTo} submitting={submitting} label="Save practice" /></form>
}

const questionSchema = z.object({ topic: z.string().min(1, 'Learning Topic is required'), question: z.string().trim().min(1, 'Question is required').max(1000), context: z.string().max(5000), answer: z.string().max(10000), status: z.enum(QUESTION_STATUSES) })
export function QuestionForm({ topics, initialValues = { topic: '', question: '', context: '', answer: '', status: 'Unanswered' }, onSubmit, submitting, serverError, cancelTo }) {
  const { register, control, handleSubmit, reset, formState: { errors } } = useForm({ resolver: zodResolver(questionSchema), defaultValues: initialValues })
  useEffect(() => reset(initialValues), [initialValues, reset])
  return <form onSubmit={handleSubmit(onSubmit)} noValidate className="space-y-3"><section className="rounded-lg bg-white p-4 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><TopicSelect control={control} topics={topics} error={errors.topic?.message} /><label className="text-sm font-semibold text-[#555]">Status<FormSelect name="status" control={control} options={QUESTION_STATUSES} className="mt-1.5" /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">Question <span className="text-red-500">*</span><textarea {...register('question')} rows="3" className={`${inputClass} resize-y`} placeholder="Write the question or doubt" /><ErrorText message={errors.question?.message} /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">Notes / context<textarea {...register('context')} rows="4" className={`${inputClass} resize-y`} placeholder="Add useful context" /></label><label className="text-sm font-semibold text-[#555] sm:col-span-2">Answer<textarea {...register('answer')} rows="6" className={`${inputClass} resize-y`} placeholder="Record the answer when you understand it" /></label></div></section>{serverError && <p className="rounded-md bg-red-50 px-4 py-3 text-sm text-red-600">{serverError}</p>}<Actions cancelTo={cancelTo} submitting={submitting} label="Save question" /></form>
}
